### PR TITLE
Rescue RbNaCl exception for EdDSA wrong key

### LINKED ISSUE #490: Rotating keys with ED25519
I'm trying to implement rotating keys, I'm not sure if I'm doing it right.

```ruby
payload = JWT.decode(token, nil, true, { algorithm: 'ED25519' }) do |_headers, payload|
  [old_public_key, public_key]
end
=> raise 'signature was forged/corrupt (RbNaCl::BadSignatureError)'
```

`decode` is supposed to test all keys with `return if Array(@key).any? { |key| verify_signature_for?(key) }` but `verify_signature_for?` will raise an error if the key is invalid instead of returning `false`.

Is it the expected behavior? If not I can submit a PR. If it is the intended behavior how should I implement rotating keys?

Thank you!

### PR DESCRIPTION
**Pull request by n-studio**
Fixes #490 

Instead of raising an error when a public key is invalid, we should return `false` so the key finder can test the next key.

### CODE REVIEW

**Review by anakinj — CHANGES_REQUESTED** [review]

**Comment by n-studio** [comment]
@anakinj Thank you for the review! I updated my code accordingly.

File: spec/jwt_spec.rb [hunk 1]
```diff
@@ -218,7 +218,7 @@
 
         it 'wrong key should raise JWT::DecodeError' do
           expect do
-            JWT.decode data[alg], wrong_key
+            JWT.decode data[alg], wrong_key, true, algorithm: alg
```
Comment (anakinj) [inline spec/jwt_spec.rb:221]: Oh, this was a good catch, the test has been wrong all the time, right. Like passing for the wrong reasons.

**Review by anakinj — APPROVED** [review]

**Comment by anakinj** [comment]
This is great stuff. Thank you for the fix.
